
/* General */
import Head from "next/head"
import InstitutionalPage from "../../components/templates/Institutional/InstitutionalPage"

const Privacy = () => {
  return (
    <>
      <Head>
        <title>RX6 - Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <InstitutionalPage />
    </>
  )
}

export default Privacy