import Head from 'next/head'
import { Container } from '../styles/global';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>RX6 - Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
        AA
      </Container>
    </div>
  )
}

export default Home;